name: CI/CD Pipeline

on:
  push:
    branches:  
      - main
      - release/*  # Wildecard is used
  pull_request:
    branches: 
      - main
    matrix:
      os: [ubuntu-latest, windows-latest, macOS-latest]
jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: ^18 # Only needed on Windows (optional on Linux/macOS)
          if: runner.os == "windows"
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      
      - name: Install Dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
