name: Lint Code Base

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Full git history needed for super-linter

      - name: Verify Solution File
        run: |
          if [ ! -f src/solution.sln ]; then
            echo "Error: Solution file not found at src/solution.sln. Please verify the path."
            exit 1
          fi
          head -n 1 src/solution.sln | grep -q "Microsoft Visual Studio Solution File"
          if [ $? -eq 1 ]; then
            echo "Error: Solution file format is invalid. Please check the file content."
            exit 1
          fi

      - name: Set failure flag
        run: echo "::set-output name=INSTALL_STYLECOP ::true"
        if: ${{ failure() }}  # Set flag only if previous step fails

      - name: Install dotnet-stylecop (if not cached)
        uses: actions/cache@v3
        with:
          path: ~/.dotnet/tools
          key: ${{ runner.os }}-dotnet-stylecop-${{ hashFiles('**/global.json') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-stylecop-

      - name: Install dotnet-stylecop (fallback)
        run: dotnet tool install --global dotnet-stylecop  # Adjust version if needed
        if: env.INSTALL_STYLECOP == 'true'  # Install only if flag is set

      - name: Restore NuGet packages
        run: dotnet restore src/solution.sln  # Adjust path if needed

      - name: Run StyleCop analysis with logging
        run: |
          dotnet stylecop src/solution.sln --rule-set=Rules.ruleset &> stylecop_analysis.log
          cat stylecop_analysis.log

      - name: Lint Code Base 
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
